services:
  - docker

before_install:
  - docker build --no-cache -t gollum-galore .
  # Don't deamonize, because we want to see the logs
  - docker run --rm --name gollum-galore -p 8080:80  -e GOLLUM_PARAMS="--allow-uploads --live-preview" -e CADDY_PARAMS="-conf /gollum/config/Caddyfile" -v $(pwd)/test/Caddyfile:/gollum/config/Caddyfile gollum-galore&
  # Wait for gollum-galore to startup
  - sleep 5
  - echo "Finish sleeping"

# Do some basic sanity checks with the container
script:
  - chmod +x test/test.sh
  - test/test.sh
